### ISSUE TITLE
create "applicants" list component

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/fuksilaiterekisteri#180]
show all users who 
are eligible
&& fresherYear === thisYear
&& belong to the study program current user has access to

note, name, email(s), student number, study program, digi skills*, has enrolled*, wants device*, device given at, device id, device distributed by

admin and staff can toggle *

**Comment by markokoskinen2037** [comment]
partial dupe: admin stuff was already done
