### ISSUE TITLE
ADD BIG ROUND BUTTONS for ADMIN

### ISSUE THREAD

**Issue by Granigan** [UniversityOfHelsinkiCS/fuksilaiterekisteri#196]
place them somewhere good

GREEN ACTIVATE SERVICE BUTTON:
- current_semester = currentyear-magicnumber(1850)
- current_year = currentyear 
- student_registration = true

RED STOP REGISTRATION:
- student_registration = false

**Comment by markokoskinen2037** [comment]
- [ ] big
- [ ] round
- [x] button
